extern int airfare(double fee);
extern int privateCar(double miles);
extern int rentalCar(int days, double pricePerDay);
extern int parkingFees(int days, double fee);
extern int taxiFees(int days, double fee);
extern int registrationFees(double fee);
extern int hotelFees(int days, double fee);
extern int eligibleDepartMeals(int depart);
extern int eligibleArrivalMeals(int arrival);
extern int mealFees(int departMeal, int arriveMeal, double departFee, double arriveFee);
