int airfare(double fee);
int privateCar(double miles);
int rentalCar(int days, double pricePerDay);
int parkingFees(int days, double fee);
int taxiFees(int days, double fee);
int registrationFees(double fee);
int hotelFees(int days, double fee);
int eligibleDepartMeals(int depart);
int eligibleArrivalMeals(int arrival);
int mealFees(int departMeal, int arriveMeal, double departFee, double arriveFee);
